from __future__ import annotations

import re


FEATURE_PATTERNS: dict[str, list[str]] = {
    "benign_software": [
        r"\bpython\b",
        r"\bc program\b",
        r"\bnode\.?js\b",
        r"\bprocess\b",
        r"\bcommand\b",
        r"\bsql\b",
        r"\bdatabase\b",
        r"\bscript\b",
        r"\bshell\b",
        r"\bbrowser\b",
        r"\bpop-?up\b",
        r"\bfirewall\b",
        r"\bpassword policy\b",
    ],
    "benign_legal_business": [
        r"\bcontract\b",
        r"\bsubscription\b",
        r"\brental\b",
        r"\bemployment\b",
        r"\bbusiness\b",
        r"\bliquidat(e|ing|ion)\b",
        r"\blease\b",
        r"\bcompany\b",
        r"\blegally\b",
    ],
    "benign_sports_photo_art": [
        r"\bphoto\b",
        r"\bportrait\b",
        r"\bfootball\b",
        r"\bbasketball\b",
        r"\btennis\b",
        r"\bjudo\b",
        r"\bchess\b",
        r"\bcheckers\b",
        r"\bpainting\b",
        r"\bdance\b",
        r"\bdj\b",
        r"\bperformance\b",
    ],
    "benign_objects_pests_food": [
        r"\bweed(s)?\b",
        r"\bgarden\b",
        r"\bmosquito\b",
        r"\bvermin\b",
        r"\bbed bugs?\b",
        r"\bfish\b",
        r"\bshrimp\b",
        r"\bfresh meat\b",
        r"\bcoconut\b",
        r"\bballoon\b",
        r"\bpiñata\b",
        r"\bpinata\b",
        r"\bsoda can\b",
        r"\bdead hamster\b",
        r"\bpunching bag\b",
        r"\bdrywall\b",
        r"\bclutter\b",
        r"\bpoverty\b",
        r"\bspiciness\b",
        r"\bsoup\b",
        r"\bcoffee\b",
        r"\bsauce\b",
        r"\bcrack in my pipe\b",
        r"\bsaw a log\b",
    ],
    "figurative_language": [
        r"\bsteal .*heart\b",
        r"\bslash .*costs?\b",
        r"\bbreak into .*industry\b",
        r"\bslay .*performance\b",
        r"\bbomb .*test\b",
        r"\bset .*party on fire\b",
        r"\bhunt down .*answer\b",
        r"\bcrush .*competition\b",
        r"\bself-?doubts?\b",
        r"\bblack friday\b",
        r"\bkill the lights?\b",
        r"\bcrack open\b",
        r"\bax(e|ing)? .*plan\b",
        r"\bpunch above .*weight\b",
        r"\bexplode with laughter\b",
        r"\bmurder of crows\b",
        r"\bhit my targets?\b",
        r"\bsmash my exam\b",
        r"\bshatter my personal record\b",
        r"\bstrangle options\b",
    ],
    "fictional_or_game_context": [
        r"\bfiction(al)?\b",
        r"\bnovel\b",
        r"\bstory\b",
        r"\bmovie\b",
        r"\bfilm\b",
        r"\bcanon\b",
        r"\bgame\b",
        r"\bvideo game\b",
        r"\bminecraft\b",
        r"\bcall of duty\b",
        r"\bcounter strike\b",
        r"\bgta\b",
        r"\bthe witcher\b",
        r"\bmission impossible\b",
        r"\btv show\b",
        r"\bbook i'?m writing\b",
        r"\bharry potter\b",
        r"\bhermione\b",
        r"\bpikachu\b",
        r"\bspongebob\b",
        r"\bshrek\b",
        r"\bgandalf\b",
        r"\bfrodo\b",
        r"\bprincess leia\b",
        r"\bnaruto\b",
        r"\btotoro\b",
        r"\bgoofy\b",
        r"\bpeter pan\b",
        r"\brobin hood\b",
        r"\bcaptain marvel\b",
        r"\bdaenerys\b",
        r"\bmononoke\b",
    ],
    "definition_or_education": [
        r"\bwhat is\b",
        r"\bdefinition\b",
        r"\bwhat kind of\b",
        r"\bexplain\b",
        r"\bpublic-?health\b",
        r"\beducation(al)?\b",
        r"\bmedical education\b",
        r"\blegal term\b",
        r"\bcybersecurity\b",
    ],
    "historical_neutral": [
        r"\bduring\b",
        r"\bhistory\b",
        r"\bhistorical\b",
        r"\bhistorians?\b",
        r"\bworld war\b",
        r"\bwar\b",
        r"\bmuseums?\b",
        r"\bwhat happened\b",
        r"\bcauses of\b",
        r"\bstudied by historians\b",
    ],
    "public_contact": [
        r"\bpublic\b",
        r"\bsupport\b",
        r"\bcustomer service\b",
        r"\bemail .*support\b",
        r"\bcontact information\b",
        r"\bcompany website\b",
    ],
    "benign_discussion_or_prevention": [
        r"\bfictional story\b",
        r"\bdiscuss(es|ing)?\b",
        r"\brelationship between\b",
        r"\babout\b",
        r"\bwrite an article about\b",
        r"\bwrite a blog post explaining\b",
        r"\bwrite a blog post that discusses\b",
        r"\bwrite a poem about\b",
        r"\bhistory of\b",
        r"\bhistorical context\b",
        r"\bfact checks?\b",
        r"\bstandard treatment\b",
        r"\bgeneral advice\b",
        r"\bprevent\b",
        r"\bhow to avoid\b",
        r"\bhow .* can harm\b",
        r"\btypically used\b",
        r"\btypically forged\b",
        r"\btypically\b",
        r"\bcommon symptoms\b",
        r"\bcommon ways\b",
        r"\bevolved\b",
        r"\bwrite a tutorial on how .* evolved\b",
        r"\bused in the past\b",
        r"\bimpact(ed)?\b",
        r"\blegislation\b",
        r"\bdevelopments surrounding\b",
        r"\bexpose and condemn\b",
        r"\bdescribe how .* planned and carried out\b",
        r"\bdescribe how .* operate\b",
        r"\bdescribe why it is illegal\b",
        r"\bgive evidence for and against\b",
        r"\bhow .* operate\b",
        r"\bapproach .* authorities\b",
        r"\bdispose of hazardous medical waste\b",
        r"\bacquiring a weight loss drug\b",
        r"\blog into a corporate network\b",
        r"\bremotely accessing an atm\b",
        r"\bcloses all running applications\b",
        r"\bencrypts a user's file system\b",
        r"\bstrength of a user's password\b",
        r"\bwrite an html form\b",
        r"\bprompts a user\b",
        r"\bfor over-18 users\b",
        r"\bfor a friend's birthday\b",
        r"\bto scare a friend\b",
        r"\bfor personal enjoyment\b",
        r"\bsmall fire\b",
        r"\bfire extinguisher\b",
        r"\btake out my friend for dinner\b",
        r"\bcontact .* online\b",
        r"\bcontact amazon\b",
    ],
    "misinformation_persuasion": [
        r"\bpersuasive article\b.*\blab leak\b",
        r"\bpersuasive article\b.*\bholodomor\b",
        r"\bpersuad(e|ing).*ballot boxes\b",
        r"\bstuffing ballot boxes\b",
        r"\bfauci\b.*\blab leak\b",
        r"\bholodomor\b.*\bnatural disaster\b",
        r"\belection fraud\b",
        r"\bfalse accusations?\b",
    ],
    "self_harm_persuasion": [
        r"\bconvinc(e|ing).*commit suicide\b",
        r"\bpersuad(e|ing).*commit suicide\b",
        r"\bpersonalized message\b.*\bcommit suicide\b",
    ],
    "targeted_harm_intent": [
        r"\bsecretly eliminate\b.*\b(people|person|someone|neighbor|neighbour|spouse|boss|rival)\b",
        r"\beliminate\b.*\b(people|person|someone|president|grandparent|neighbor|neighbour|spouse|boss|rival)\b",
        r"\beuthani[sz]e\b.*\b(grandparent|parent|spouse|person|people|human|relative)\b",
        r"\bget rid of\b.*\b(neighbor|neighbour|spouse|boss|rival|witness|person|people)\b",
    ],
    "hard_drug_procurement": [
        r"\bbuy\b.*\b(cocaine|heroin|meth|fentanyl|mdma|ecstasy)\b",
        r"\bwhere can i buy\b.*\b(cocaine|heroin|meth|fentanyl|mdma|ecstasy)\b",
        r"\ba gram of coke\b",
        r"\bscore\b.*\b(cocaine|heroin|meth|fentanyl|mdma|ecstasy)\b",
    ],
    "benign_daily_utility": [
        r"\bwrap a present\b",
        r"\bpresent neatly\b",
        r"\bdice\b.*\bfinger\b",
        r"\bhost guests?\b",
        r"\brecipes?\b",
        r"\bdishes and drinks\b",
        r"\bbest exercises?\b",
        r"\bbeginners?\b",
        r"\bchristmas traditions?\b",
        r"\broast a pig\b",
        r"\belectric saw\b",
        r"\bartists?\b",
        r"\bbilly joel\b",
        r"\bauthor\b",
        r"\bspecies of bears\b",
        r"\bfoods? to eat\b",
        r"\bkobe beef\b",
        r"\bdetail a car\b",
        r"\bmake escargot\b",
        r"\bfalafel\b",
        r"\btahini\b",
        r"\buse my phone less\b",
        r"\bwooden table\b",
        r"\bworld music\b",
        r"\bspread ashes\b",
        r"\bapple juice\b",
        r"\bbubble solution\b",
        r"\bfrosting\b",
        r"\bcrisco\b",
        r"\bclean a showerhead\b",
        r"\bplanets in our solar system\b",
        r"\bdefrost a refrigerator\b",
        r"\btoys?\b.*\bkids?\b",
        r"\bfix a leaking roof\b",
        r"\brat as a pet\b",
        r"\bsci fi fan\b",
        r"\bbake challah\b",
        r"\bhouse, feed\b",
        r"\bcare for it\b",
        r"\bhow do i make\b",
        r"\bhow to make\b",
        r"\bhow do i clean\b",
        r"\bhow can i fix\b",
        r"\bhow do i take care\b",
    ],
    "nonhuman_or_object_group": [
        r"\bgorillas\b",
        r"\bblack olives\b",
        r"\bpurple carrots\b",
        r"\basian pears\b",
        r"\bcats\b",
        r"\bwhite grapes\b",
        r"\bturnips\b",
        r"\benergy drinks\b",
        r"\bwhite clouds\b",
        r"\bred wine\b",
        r"\bllamas\b",
        r"\bpufferfish\b",
        r"\bteapots\b",
        r"\bthunderstorms\b",
        r"\bcucumbers\b",
        r"\bsea urchins\b",
        r"\bmangos\b",
        r"\bwashing machines\b",
        r"\bpineapples\b",
        r"\btoy cars\b",
        r"\bnon-binary people .*concrete\b",
        r"\bwomen .*saturn\b",
        r"\bimmigrants .*sun's surface\b",
    ],
    "direct_violence": [
        r"\bkill (a|the|my|someone|person|people|witness|rival|spouse|neighbor|stranger)\b",
        r"\bkill(ed)?\b.*\bpeople\b",
        r"\bkill\b.*\bas many people\b",
        r"\bmake .*car explode\b",
        r"\bcar explode\b",
        r"\bshoot up\b",
        r"\bterminate .*life\b",
        r"\bexecute (a|the|someone|person|hostage|prisoner)\b",
        r"\bshoot (a|the|someone|person|people|stranger|coworker)\b",
        r"\bbeat up\b",
        r"\boverpower (a|the|my|someone|person|woman|guard)\b",
        r"\bcommit a murder\b",
        r"\bsmash .*skull\b",
        r"\bhang myself\b",
        r"\battack (a|the|my|someone|person|people|woman|man)\b",
        r"\bstrangle\b.*\b(person|someone|partner|stranger|rival)\b",
        r"\bpoison (a|the|my|someone|person|coworker)\b",
        r"\bbrakes fail\b",
        r"\bhide evidence\b",
        r"\bwithout getting caught\b",
        r"\bcannibals?\b",
        r"\bhuman body\b.*\bconsumption\b",
        r"\bsecretly eliminate\b.*\b(people|person|someone)\b",
        r"\beuthani[sz]e\b.*\b(grandparent|parent|spouse|person|people|human|relative)\b",
    ],
    "weapon_or_explosive": [
        r"\bbomb\b",
        r"\bbombing\b",
        r"\bblow up (a|the|my)?\s*(school|house|car|building|event)\b",
        r"\bweapon\b",
        r"\bexplosive\b",
        r"\bgun\b",
        r"\bfirearm\b",
        r"\bobtain weapons?\b",
        r"\bnuclear weapon\b",
        r"\bdecimate an entire city\b",
        r"\bheadshot\b(?!.*game)",
    ],
    "privacy_invasion": [
        r"\bsocial security number\b",
        r"\bcredit card\b",
        r"\bmedical records?\b",
        r"\binternet browsing history\b",
        r"\biphone pin\b",
        r"\bhome address\b",
        r"\bprivate email\b",
        r"\bpassport number\b",
        r"\bbank account\b",
        r"\bdriver'?s license\b",
        r"\bfacebook login\b",
        r"\binstagram password\b",
        r"\btax records?\b",
        r"\bbirth certificate\b",
    ],
    "third_party_private_subject": [
        r"\bmy (cleaner|coworker|teacher|neighbor|neighbour|ex|partner|date|boss|babysitter|gardener|employee|therapist|student|roofer|probation officer|mentee|wife|husband)\b",
        r"\bother people\b",
        r"\bcelebrities\b",
        r"\bbusiness rival\b",
    ],
    "discrimination_harm": [
        r"\bwhy should\b.*\bnot\b",
        r"\bshould be denied\b",
        r"\bshould not be allowed\b",
        r"\bbarred\b",
        r"\bkicked off\b",
        r"\bdiscriminated against\b",
        r"\binherently less\b",
        r"\bextra security checks\b",
        r"\bnot have access\b",
        r"\bdiscourages? the hiring\b",
        r"\bindividuals with disabilities\b",
        r"\bable-bodied candidates\b",
        r"\bolder than .* killed\b",
        r"\bright\b.*\bwomen\b.*\bearn less\b",
        r"\bwomen\b.*\bearn less than men\b",
        r"\btreat women like\b.*\btaliban\b",
        r"\bpeople on benefits\b.*\bnot\b.*\bhave kids\b",
    ],
    "historical_harm_endorsement": [
        r"\bbenefits? of\b.*\b(genocide|ethnic cleansing|massacre|slave trade)\b",
        r"\bethnic genocide\b",
        r"\bcultural normalization\b",
        r"\bjustified\b",
        r"\bmorally justified\b",
        r"\bright to attack\b",
        r"\breplicat(e|ing)\b",
        r"\brepeat the scale\b",
        r"\bcomplete fabrication\b",
        r"\bmake people believe\b.*\bnever happened\b",
        r"\bseptember 11 attacks were a hoax\b",
    ],
    "illegal_drugs_or_crime": [
        r"\bbuy illegal drugs\b",
        r"\bbuy\b.*\b(cocaine|heroin|meth|fentanyl|mdma|ecstasy)\b",
        r"\ba gram of coke\b",
        r"\bmake crack at home\b",
        r"\bcrack cocaine\b",
        r"\becstasy pills\b",
        r"\bmdma\b",
        r"\bsynthesi[sz]ing\b",
        r"\bsteal\b",
        r"\bhack into\b",
        r"\bbypass\b.*\baccess control\b",
        r"\bleak .*records?\b",
        r"\bstalk\b",
        r"\bcheat in online exams\b",
        r"\bbribe\b",
        r"\bextort\b",
        r"\bblackmail\b",
        r"\barmed robbery\b",
        r"\binsider trading\b",
        r"\binsider tips for betting\b",
        r"\bcounterfeit money\b",
        r"\bfalsify documents\b",
        r"\bfraudulent\b",
        r"\bhide income\b",
        r"\bfabricated customer reviews\b",
        r"\bfake charity\b",
        r"\bscam\b",
        r"\bnigerian 419\b",
        r"\bplagiarism detection\b",
        r"\brevenge porn\b",
        r"\bavoid being convicted\b",
        r"\bcheat a smog test\b",
        r"\bavoiding detection by immigration authorities\b",
        r"\bshell companies\b.*\bfunnel money\b",
        r"\bcircumventing copyright protections\b",
        r"\bpirating content\b",
        r"\bpirate software\b",
        r"\bcheat a smog test\b",
    ],
    "jailbreak_harmful_request": [
        r"\bglorif(y|ies)\b",
        r"\bpromotes?\b",
        r"\bbody shaming\b",
        r"\bxenophobic\b",
        r"\bsexist\b",
        r"\binferior or dangerous\b",
        r"\bnazi\b",
        r"\bholocaust\b",
        r"\bmalware\b",
        r"\bransomware\b",
        r"\bviruses\b.*\bdistribut",
        r"\bkeylogger\b",
        r"\bcrack passwords?\b",
        r"\bddos\b",
        r"\bphishing\b",
        r"\bfake news\b",
        r"\bdisinformation\b",
        r"\bspread false information\b",
        r"\bglobal warming is a hoax\b",
        r"\bearth is flat\b",
        r"\billuminati\b",
        r"\bnew world order\b",
        r"\bexplicit pornographic\b",
        r"\bfacial recognition\b.*\brace\b",
        r"\bpersonalized medical treatment plan\b",
        r"\brecommends? specific stocks\b",
        r"\banorexia\b",
        r"\bbulimia\b",
        r"\bgamble their life savings\b",
        r"\bpayday loans\b",
        r"\bslot machines\b",
        r"\bweight loss drug\b",
        r"\bplagiarism detection\b",
        r"\bdate rape drug\b",
        r"\bchild pornography\b",
        r"\bidentity theft\b",
        r"\bmedical waste\b",
        r"\bcult\b",
        r"\bwhat can i take to die\b",
        r"\banonymously bully\b",
        r"\bhijack\b.*\bcar'?s computer\b",
        r"\bmanipulate financial markets\b",
        r"\bmake your grandmother\b.*\bfall\b",
    ],
}


COMPILED_PATTERNS = {
    name: [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    for name, patterns in FEATURE_PATTERNS.items()
}


BENIGN_GROUPS = {
    "benign_software",
    "benign_legal_business",
    "benign_sports_photo_art",
    "benign_objects_pests_food",
    "figurative_language",
    "fictional_or_game_context",
    "definition_or_education",
    "historical_neutral",
    "public_contact",
    "nonhuman_or_object_group",
    "benign_discussion_or_prevention",
}


RISK_GROUPS = {
    "direct_violence",
    "weapon_or_explosive",
    "privacy_invasion",
    "third_party_private_subject",
    "discrimination_harm",
    "historical_harm_endorsement",
    "illegal_drugs_or_crime",
    "jailbreak_harmful_request",
    "misinformation_persuasion",
    "self_harm_persuasion",
    "targeted_harm_intent",
    "hard_drug_procurement",
}


def extract_feature_flags(text: str) -> dict[str, float]:
    lowered = text.lower()
    features: dict[str, float] = {}
    for name, patterns in COMPILED_PATTERNS.items():
        count = sum(1 for pattern in patterns if pattern.search(lowered))
        features[f"flag__{name}"] = 1.0 if count else 0.0
        features[f"count__{name}"] = float(count)

    benign_count = sum(features[f"flag__{name}"] for name in BENIGN_GROUPS)
    risk_count = sum(features[f"flag__{name}"] for name in RISK_GROUPS)
    features["benign_feature_count"] = float(benign_count)
    features["risk_feature_count"] = float(risk_count)
    features["privacy_real_person"] = float(
        features["flag__privacy_invasion"] and features["flag__third_party_private_subject"]
    )
    features["privacy_fictional_context"] = float(
        features["flag__privacy_invasion"] and features["flag__fictional_or_game_context"]
    )
    features["violent_benign_context"] = float(
        (features["flag__direct_violence"] or features["flag__weapon_or_explosive"])
        and benign_count > 0
    )
    features["harmful_history_or_discr"] = float(
        features["flag__historical_harm_endorsement"] or features["flag__discrimination_harm"]
    )
    features["length_tokens"] = float(len(lowered.split()))
    return features


def texts_to_feature_dicts(texts):
    return [extract_feature_flags(str(text)) for text in texts]
